Repository googleapis/python-billing, pull requests merged in 2020-05, with the labels that each got.

#15 feat: release as production/stable
  .repo-metadata.json
  README.rst
  noxfile.py
  setup.py
Labels: cla: yes

#19 feat: add mtls support
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  CONTRIBUTING.rst
  MANIFEST.in
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/billing/__init__.py
  google/cloud/billing_v1/__init__.py
  google/cloud/billing_v1/services/__init__.py
  google/cloud/billing_v1/services/cloud_billing/__init__.py
  google/cloud/billing_v1/services/cloud_billing/client.py
  google/cloud/billing_v1/services/cloud_billing/pagers.py
  google/cloud/billing_v1/services/cloud_billing/transports/__init__.py
  google/cloud/billing_v1/services/cloud_billing/transports/base.py
  google/cloud/billing_v1/services/cloud_billing/transports/grpc.py
  google/cloud/billing_v1/services/cloud_catalog/__init__.py
  google/cloud/billing_v1/services/cloud_catalog/client.py
  google/cloud/billing_v1/services/cloud_catalog/pagers.py
  google/cloud/billing_v1/services/cloud_catalog/transports/__init__.py
  google/cloud/billing_v1/services/cloud_catalog/transports/base.py
  google/cloud/billing_v1/services/cloud_catalog/transports/grpc.py
  google/cloud/billing_v1/types/__init__.py
  google/cloud/billing_v1/types/cloud_billing.py
  google/cloud/billing_v1/types/cloud_catalog.py
  mypy.ini
  noxfile.py
  scripts/fixup_keywords.py
  setup.cfg
  setup.py
  synth.metadata
  synth.py
  tests/unit/billing_v1/test_cloud_billing.py
  tests/unit/billing_v1/test_cloud_catalog.py
Labels: cla: yes, context: none

#21 chore: use latest sphinx
  docs/conf.py
  noxfile.py
  synth.metadata
  synth.py
Labels: automerge, cla: yes
