Repository googleapis/python-billing, pull requests merged in 2021-04, with the labels that each got.

#53 chore: add tarfile
  billing-v1-py.tar.gz
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: none

#54 chore: remove .tar.gz
  billing-v1-py.tar.gz
  google/cloud/billing_v1/__init__.py
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: none

#57 chore: add license headers
  .pre-commit-config.yaml
  docs/conf.py
  google/cloud/billing_v1/__init__.py
  synth.metadata
Labels: api: cloudbilling, cla: yes, context: partial

#60 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudbilling, automerge, cla: yes

#61 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/header-checker-lint.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  owlbot.py
  renovate.json
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes
